### ISSUE TITLE
Code releasing problem

### ISSUE THREAD

**Issue by xl-huo** [2120171054/Global-Aware-Registration-of-Less-Overlap-RGB-D-Scans#1]
First, thank you for this solid work!

Since this work is accepted by CVPR22, I'm wondering when will the code be released?

Looking forward to your reply!

**Comment by 2120171054** [comment]
Thank you for your attention to our work.

We will release our code when we return to our campus in around September, as our code and data are stored in the server in the campus. 

Unfortunately, we had to leave our campus due to the COVID-19 in recent months. Sorry for not releasing the code in time and we will finish it as soon as possible.




---------------- 

---------- Origin message ----------
>From："Huo Xiaoliang" ***@***.***>
>To："2120171054/Global-Aware-Registration-of-Less-Overlap-RGB-D-Scans" ***@***.***>
>Subject：[2120171054/Global-Aware-Registration-of-Less-Overlap-RGB-D-Scans] Code releasing problem (Issue #1)
>Date：2022-07-11 11:08:58First, thank you for this solid work!

Since this work is accepted by CVPR22, I'm wondering when will the code be released?

Looking forward to your reply!

--
Reply to this email directly or view it on GitHub:
https://github.com/2120171054/Global-Aware-Registration-of-Less-Overlap-RGB-D-Scans/issues/1

**Comment by detectRecog** [comment]
Any news?
